#ifndef SHARED_DEFS_H
#define SHARED_DEFS_H

enum pageId{
    INTRO_PAGE,
	COMPETITION_STATUS_PAGE,
    DISCIPLINE_TYPE_PAGE,
	DISCIPLINE_PAGE,
    RESULT_RECORD_PAGE,
	PLACE_RECORD_PAGE,
    FINAL_PAGE,
};

#endif // SHARED_DEFS_H
